env:
  browser: true
  es6: true
globals:
  d3: false
  CGView: false
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2015
rules:
  no-console: warn
  # valid-jsdoc: warn
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  prefer-const: error
  prefer-rest-params: error
  prefer-spread: error
  no-var: error
  prefer-numeric-literals: error
  prefer-template: error
  template-curly-spacing: error
  dot-notation: error
  no-multi-assign: error
  eqeqeq: error
  no-nested-ternary: error
  no-unneeded-ternary: error
  no-mixed-operators: error
  nonblock-statement-body-position: error
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: true
  implicit-arrow-linebreak:
    - error
    - beside
  spaced-comment:
    - warn
    - always
    - exceptions:
      - '/'
  space-before-blocks: error
  keyword-spacing: error
  space-infix-ops: error
  eol-last: warn
  no-trailing-spaces: warn
  no-whitespace-before-property: error
  padded-blocks:
    - warn
    - blocks: never
      classes: always
  comma-spacing: warn
  comma-style: warn
  comma-dangle: warn
  key-spacing: warn
  camelcase: error
  new-cap: error


